multiversx/mx-sdk-go

tests/address_test.go
=> Fixed tests

blockchain/addressGenerator.go, blockchain/interface.go, blockchain/proxy.go, blockchain/shardCoordinator.go, data/transaction.go, tests/address_test.go
General refactor and renaming of various components and functions
=> General Refactor

blockchain/addressGenerator.go, blockchain/interface.go, blockchain/proxy.go, blockchain/shardCoordinator.go, blockchain/txSinger.go, data/transaction.go, interactors/errors.go, interactors/interface.go, interactors/mock/proxyStub.go, interactors/mock/txSignerStub.go, interactors/transaction.go, interactors/transaction_test.go, tests/address_test.go
Adding interactors and unit tests
=> Interactors

.github/workflows/pr-tests.yml, Makefile
Added Github action to run unit tets
=> Github action for unit tests

interactors/addressNonceHandler.go, interactors/errors.go, interactors/nonceTransactionsHandler.go, interactors/nonceTransactionsHandler_test.go
- added nonce transactions handler implementation
=> Nonce-transactions-handler

data/account.go
Expanded the Account response data with new fields:
CodeMetadata []byte json:"codeMetadata"
Username string json:"username"
DeveloperReward string json:"developerReward"
OwnerAddress string json:"ownerAddress"
=> updated account response fields

examples/examplesFlowWalletTracker/main.go, interactors/nonceTransactionsHandler.go, workflows/walletsTracker.go
- replaced time.After with time.Timer
=> Replaced time.After with time.Timer

builders/baseBuilder.go, builders/baseBuilder_test.go, builders/errors.go, builders/interface.go, builders/txDataBuilder.go, builders/txDataBuilder_test.go, builders/vmQueryBuilder.go, builders/vmQueryBuilder_test.go, core/variables.go, examples/examplesAccount/main.go, examples/examplesBlock/main.go, examples/examplesFlowWalletTracker/main.go, examples/examplesTransaction/main.go, examples/examplesVMQuery/main.go, examples/examplesWallet/main.go, interactors/transaction.go, storage/mapCacher.go, workflows/walletsTracker.go
- added transaction data builder
=> Added transaction data builder

blockchain/proxy.go, blockchain/proxy_test.go, blockchain/shardCoordinator.go, core/constants.go, core/variables.go, data/account.go, data/address.go, examples/examplesAccount/main.go, examples/examplesBlock/main.go, examples/examplesFlowWalletTracker/main.go, examples/examplesTransaction/main.go, examples/examplesVMQuery/main.go, interactors/addressNonceHandler.go, interactors/errors.go, interactors/interface.go, interactors/mock/proxyStub.go, interactors/nonceTransactionsHandler.go, interactors/nonceTransactionsHandler_test.go, interactors/transaction.go, interactors/transaction_test.go, interactors/wallet.go, serde/deserializer_test.go, serde/sourceBuffer.go, serde/testingMocks/entities.go, workflows/interface.go, workflows/moveBalanceHandler.go, workflows/walletsTracker.go
- added context.Context parameter on all exposed Proxy functions
=> Added context.Context parameter on all exposed Proxy functions

core/interface.go, data/address.go
-added method ConvertFromByteSliceToArray for Address Handler
=> ConvertFromByteSliceToArray in AddressHandler

core/interface.go, data/address.go
- changed the addressHandler implementation and interface
=> AddressHandler changes

blockchain/errors.go, blockchain/export_test.go, blockchain/interface.go, blockchain/proxyWithCacher.go, blockchain/proxyWithCacher_test.go
- added a decorator for current implementation of elrond proxy that is caching:
NetworkConfig
=> Proxy with cacher

core/polling/errors.go, core/polling/interface.go, core/polling/mock/executorStub.go, core/polling/pollingHandler.go, core/polling/pollingHandler_test.go
- added pooling handler implementation (moved from elrond-eth-bridge)
=> pooling handler implementation

aggregator/binance.go, aggregator/binance_test.go, aggregator/constants.go, aggregator/converters.go, aggregator/errors.go, aggregator/httpResponseGetter.go, aggregator/httpResponseGetter_test.go, aggregator/interface.go, aggregator/mock/httpResponseGetterStub.go
- implementation of the Binance price fetcher
=> Binance price fetcher

interactors/wallet.go
- fixed data race condition & wallet interactor operation
=> Fixed data race condition & wallet interactor operation

aggregator/binance.go, aggregator/binance_test.go, aggregator/httpResponseGetter.go, aggregator/httpResponseGetter_test.go, aggregator/interface.go, aggregator/mock/httpResponseGetterStub.go
- added context on aggregator operations
=> Context operation on aggregator

blockchain/interface.go, interactors/mock/proxyStub.go
- added ExecuteVMQuery in proxy interface
=> add ExecuteVMQuery in proxy interface

aggregator/binance.go, aggregator/binance_test.go, aggregator/bitfinex.go, aggregator/bitfinex_test.go, aggregator/computers.go, aggregator/computers_test.go, aggregator/cryptocom.go, aggregator/cryptocom_test.go, aggregator/errors.go, aggregator/gemini.go, aggregator/gemini_test.go, aggregator/interface.go, aggregator/mock/priceFetcherStub.go, aggregator/priceAggregator.go, aggregator/priceAggregator_test.go, blockchain/proxyWithCacher.go, core/variables.go
=> Price aggregator

aggregator/computers.go, aggregator/computers_test.go, aggregator/errors.go, aggregator/priceAggregator.go
- made the median computation function more robust
=> Made the median computation function more robust

aggregator/binance.go, aggregator/binance_test.go, aggregator/bitfinex.go, aggregator/bitfinex_test.go, aggregator/converters.go, aggregator/gemini.go, aggregator/gemini_test.go, aggregator/hitbtc.go, aggregator/huobi.go, aggregator/huobi_test.go, aggregator/kraken.go, aggregator/kraken_test.go, aggregator/okex.go, aggregator/okex_test.go
=> More exchanges

aggregator/converters.go, aggregator/converters_test.go, aggregator/errors.go, aggregator/interface.go, aggregator/mock/priceNotifeeStub.go, aggregator/priceNotifier.go, aggregator/priceNotifier_test.go
=> Added price notifier

aggregator/fetchers/baseFetcher.go, aggregator/fetchers/baseFetcher_test.go, aggregator/fetchers/binance.go, aggregator/fetchers/bitfinex.go, aggregator/fetchers/constants.go, aggregator/fetchers/cryptocom.go, aggregator/fetchers/factory.go, aggregator/fetchers/factory_test.go, aggregator/fetchers/fetchers_test.go, aggregator/fetchers/gemini.go, aggregator/fetchers/hitbtc.go, aggregator/fetchers/huobi.go, aggregator/fetchers/kraken.go, aggregator/fetchers/okex.go, aggregator/priceNotifier.go, aggregator/priceNotifier_test.go, examples/examplesPriceAggregator/main.go
- example for price aggregator fetching mechanism
- minor fixes and adjustments
=> Example price aggregator

aggregator/computers.go, aggregator/computers_test.go, aggregator/errors.go, aggregator/export_test.go, aggregator/httpResponseGetter_test.go, aggregator/interface.go, aggregator/mock/priceNotifeeStub.go, aggregator/priceAggregator.go, aggregator/priceAggregator_test.go, aggregator/priceNotifier.go, aggregator/priceNotifier_test.go, examples/examplesPriceAggregator/main.go
- made the price notifee able to notify automatically after a period of time even if the price did not changed
- made the notifee be able to take a slice of pairs
- added denominator factor for each pair
=> Price notifier refactor

aggregator/notifees/elrondNotifee.go, aggregator/notifees/elrondNotifee_test.go, aggregator/notifees/errors.go, aggregator/notifees/interface.go, testsCommon/privateKeyStub.go, testsCommon/publicKeyStub.go, testsCommon/txBuilderStub.go, testsCommon/txNonceHandlerStub.go
- added Elrond notifee for the price aggregator sub-system
=> Elrond notifee

storage/mapCacher.go
added missing mutex lock into mapCacher/Keys method
=> Missing mutex lock

blockchain/elrondBaseProxy.go, blockchain/elrondBaseProxy_test.go, blockchain/errors.go, blockchain/interface.go, blockchain/proxy.go, blockchain/proxy_test.go, core/http/clientWrapper.go, core/http/clientWrapper_test.go, testsCommon/httpClientWrapperStub.go
- added headers parameters set on the REST-API get & post operations
=> Header parameters on REST-API requests

.github/workflows/create_release.yml
- added create release workflow
=> Added create release workflow

.github/workflows/create_release.yml
=> Create release workflow fix

aggregator/errors.go, aggregator/fetchers/baseFetcher.go, aggregator/fetchers/baseFetcher_test.go, aggregator/fetchers/binance.go, aggregator/fetchers/bitfinex.go, aggregator/fetchers/cryptocom.go, aggregator/fetchers/factory.go, aggregator/fetchers/fetchers_test.go, aggregator/fetchers/gemini.go, aggregator/fetchers/hitbtc.go, aggregator/fetchers/huobi.go, aggregator/fetchers/kraken.go, aggregator/fetchers/maiar.go, aggregator/fetchers/okex.go, aggregator/interface.go, aggregator/mock/priceFetcherStub.go, aggregator/priceAggregator.go, aggregator/priceNotifier.go, aggregator/priceNotifier_test.go, examples/examplesPriceAggregator/main.go
Added new method AddPair to PriceFetcher interface in order to set what pairs the specific exchange supports
=> Each exchange now supports for the registered pairs

.github/workflows/golangci-lint.yml, data/hyperblock.go
Hi, nothing special
Just missing Timestamp field in HyperBlock structure
You can see it in example -> https://gateway.elrond.com/hyperblock/by-nonce/10800000
=> fix: add missing timestamp field in HyperBlock model

interactors/testdata/testWithKind.json, interactors/wallet.go, interactors/wallet_test.go
add support (backward compatible) for new JSON files
=> add support for new json files

core/http/clientWrapper.go
- fixed the http user agent string
More info here: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/User-Agent
=> Fixed the http user agent string

core/http/clientWrapper.go
Merge main into guardians feature support branch
=> Merge main freeze account

go.mod, go.sum, testsCommon/nodesCoordinatorStub.go
- integrated latest mx-chain-go v1.7.12
=> Integrated latest mx-chain-go v1.7.12

blockchain/interface.go, testsCommon/proxyStub.go
=> Fix #198: Make blockchain.proxy implement blockchain.Proxy interface
